var shopper = {
    fruit: "mango",
    amount: 10,
    vegetable: false,
    groceryCart: [
        "milk",
        "salt",
        "mango",
        "beans"
    ],

    description: function() {
        document.write();
    }
}


var person =  {
    firstname: "Mark",
    lastname: "Corpuz",
    age: 31,
    haircolor: "black",
    fullname: function () {
    }
};

console.log(person.firstname+ " "+ person.lastname+" "+ "is"+ " "+ person.age)