var shopper = {
    fruit: "mango",
    amount: 10,
    vegetable: false,
    groceryCart: [
        "milk",
        "salt",
        "mango",
        "beans"
    ],

    description: function() {
        document.write( )
    }
}

 console.log(shopper);

var person =  {
    firstname: "Mark",
    lastname: "Corpuz",
    age: 31,
    haircolor: "black",
    fullname: function () {
        document.write(this.firstname+ " " +this.lastname)
        ;
    }
};
person.fullname();